<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { NAlert, NButton, NInput, NModal } from 'naive-ui'
import { api, type Device } from '@/lib/api'
const devices=ref<Device[]>([]);const error=ref('');const loading=ref(false);const editing=ref<Device|null>(null);const form=reactive({display_name:'',note:''})
function time(ms:number){return new Date(ms).toLocaleString()} async function load(){loading.value=true;try{devices.value=(await api.devices()).items}catch(e){error.value=e instanceof Error?e.message:'无法读取设备'}finally{loading.value=false}}
function edit(device:Device){editing.value=device;form.display_name=device.display_name;form.note=device.note}async function save(){if(!editing.value)return;loading.value=true;try{await api.updateDevice(editing.value.id,{display_name:form.display_name,note:form.note});editing.value=null;await load()}catch(e){error.value=e instanceof Error?e.message:'更新失败'}finally{loading.value=false}}
onMounted(load)
</script>
<template><section class="page"><header class="page-heading"><div><p class="eyebrow">客户端识别</p><h1>设备管理</h1></div><NButton :loading="loading" @click="load">刷新</NButton></header><NAlert v-if="error" type="error" class="form-alert">{{ error }}</NAlert><div class="table-wrap"><table><thead><tr><th>IP</th><th>显示名称</th><th>主机名</th><th>来源</th><th>24h 查询</th><th>最近出现</th><th></th></tr></thead><tbody><tr v-for="device in devices" :key="device.id"><td class="mono">{{ device.ip }}</td><td>{{ device.display_name || '-' }}</td><td>{{ device.hostname || '-' }}</td><td>{{ device.source }}</td><td>{{ device.query_count_24h }}</td><td>{{ time(device.last_seen_at_ms) }}</td><td><NButton size="small" @click="edit(device)">备注</NButton></td></tr><tr v-if="!loading&&!devices.length"><td colspan="7" class="empty-cell">尚未观察到 DNS 客户端</td></tr></tbody></table></div><NModal :show="Boolean(editing)" @update:show="(show) => { if (!show) editing = null }" preset="card" title="维护设备信息" class="rule-modal"><div class="form-grid"><label>显示名称<NInput v-model:value="form.display_name" maxlength="128" /></label><label>备注<NInput v-model:value="form.note" maxlength="500" /></label></div><div class="modal-actions"><NButton @click="editing=null">取消</NButton><NButton type="primary" :loading="loading" @click="save">保存</NButton></div></NModal></section></template>
