<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { NAlert, NButton, NSpin } from 'naive-ui'
import { api } from '@/lib/api'

const loading = ref(true); const error = ref(''); const summary = ref({ query_count: 0, average_latency_us: 0 }); const domains = ref<Array<{ value: string | number; query_count: number }>>([]); const clients = ref<Array<{ value: string | number; query_count: number }>>([]); const routes = ref<Array<{ value: string | number; query_count: number }>>([])
async function load() { loading.value = true; error.value = ''; try { const [nextSummary, nextDomains, nextClients, nextRoutes] = await Promise.all([api.summary(), api.statistic('domains'), api.statistic('clients'), api.statistic('routes')]); summary.value = nextSummary; domains.value = nextDomains.items; clients.value = nextClients.items; routes.value = nextRoutes.items } catch (e) { error.value = e instanceof Error ? e.message : '无法加载统计数据' } finally { loading.value = false } }
onMounted(load)
</script>
<template><section class="page"><header class="page-heading"><div><p class="eyebrow">运行概览</p><h1>DNS 查询状态</h1></div><NButton @click="load" :loading="loading">刷新</NButton></header><NAlert v-if="error" type="error" class="form-alert">{{ error }}</NAlert><NSpin :show="loading"><div class="metric-grid"><article><span>近 24 小时查询</span><strong>{{ summary.query_count.toLocaleString() }}</strong></article><article><span>平均延迟</span><strong>{{ summary.average_latency_us }} <small>us</small></strong></article><article><span>路由种类</span><strong>{{ routes.length }}</strong></article></div><div class="summary-grid"><section><h2>Top 域名</h2><ol class="rank-list"><li v-for="item in domains" :key="String(item.value)"><span>{{ item.value }}</span><b>{{ item.query_count }}</b></li><li v-if="!domains.length" class="muted">暂无查询数据</li></ol></section><section><h2>Top 客户端</h2><ol class="rank-list"><li v-for="item in clients" :key="String(item.value)"><span>{{ item.value }}</span><b>{{ item.query_count }}</b></li><li v-if="!clients.length" class="muted">暂无查询数据</li></ol></section><section><h2>路由分布</h2><ol class="rank-list"><li v-for="item in routes" :key="String(item.value)"><span class="route-tag" :class="String(item.value)">{{ item.value }}</span><b>{{ item.query_count }}</b></li><li v-if="!routes.length" class="muted">暂无查询数据</li></ol></section></div></NSpin></section></template>
