<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { NAlert, NButton, NInput, NSelect, NSwitch } from 'naive-ui'
import { api, eventStream, type QueryEvent } from '@/lib/api'
import { formatLatencyMs } from '@/lib/format'

const rows = ref<QueryEvent[]>([]); const cursor = ref(''); const pageSize = ref(100); const clientIP = ref(''); const route = ref(''); const loading = ref(false); const error = ref(''); const live = ref(false); const paused = ref(false); const streamState = ref('未连接'); let stream: EventSource | undefined
const routeOptions = [{ label: '全部路由', value: '' }, { label: '本地', value: 'local' }, { label: '远程', value: 'remote' }, { label: '拦截', value: 'block' }]
function formatTime(ms: number) { return new Date(ms).toLocaleString() }
async function load(nextCursor = '') { loading.value = true; error.value = ''; try { const page = await api.queries({ limit: pageSize.value, cursor: nextCursor, client_ip: clientIP.value, route: route.value }); const items = page.items ?? []; rows.value = nextCursor ? [...rows.value, ...items] : items; cursor.value = page.next_cursor ?? '' } catch (e) { error.value = e instanceof Error ? e.message : '无法加载查询日志' } finally { loading.value = false } }
function closeStream() { stream?.close(); stream = undefined; streamState.value = '已断开' }
function toggleLive(enabled: boolean) { if (!enabled) { closeStream(); return }; streamState.value = '连接中'; stream = eventStream(); stream.onopen = () => { streamState.value = '已连接' }; stream.onerror = () => { streamState.value = '重连中' }; stream.addEventListener('connected', () => { streamState.value = '已连接' }); stream.addEventListener('query', (message) => { if (paused.value) return; const event = JSON.parse((message as MessageEvent).data) as QueryEvent; rows.value = [event, ...rows.value].slice(0, 300) }) }
onMounted(() => load()); onBeforeUnmount(closeStream)
</script>
<template><section class="page"><header class="page-heading"><div><p class="eyebrow">查询审计</p><h1>查询日志</h1></div><div class="inline-controls"><span class="connection" :class="{ online: streamState === '已连接' }">{{ streamState }}</span><NSwitch v-model:value="live" @update:value="toggleLive"><template #checked>实时</template><template #unchecked>实时</template></NSwitch><NSwitch v-model:value="paused" :disabled="!live"><template #checked>暂停</template><template #unchecked>暂停</template></NSwitch></div></header><div class="filters"><NInput v-model:value="clientIP" placeholder="客户端 IP" clearable /><NSelect v-model:value="route" :options="routeOptions" /><NSelect v-model:value="pageSize" :options="[{ label: '每页 50 条', value: 50 }, { label: '每页 100 条', value: 100 }, { label: '每页 200 条', value: 200 }]" /><NButton type="primary" :loading="loading" @click="load()">筛选</NButton></div><NAlert v-if="error" type="error" class="form-alert">{{ error }}</NAlert><div class="table-wrap queries-table-wrap"><table><thead><tr><th>时间</th><th>客户端</th><th>域名</th><th>类型</th><th>结果</th><th>路由 / 上游</th><th>缓存</th><th>延迟</th></tr></thead><tbody><tr v-for="row in rows" :key="row.event_id"><td>{{ formatTime(row.timestamp_unix_ms) }}</td><td>{{ row.client_ip }}</td><td class="mono">{{ row.qname }}</td><td>{{ row.qtype }}</td><td>{{ row.rcode }}</td><td class="route-upstream"><div class="route-cell"><span class="route-tag" :class="row.route">{{ row.route }}</span><span class="route-separator" aria-hidden="true"></span><span class="upstream-tag mono" :title="row.upstream_tag || '未记录上游'">{{ row.upstream_tag || '-' }}</span></div></td><td>{{ row.cache_hit ? '命中' : '-' }}</td><td>{{ formatLatencyMs(row.latency_us) }}</td></tr><tr v-if="!loading && !rows.length"><td colspan="8" class="empty-cell">暂无查询日志</td></tr></tbody></table></div><footer class="table-footer"><span>已显示 {{ rows.length }} 条；查询使用 cursor 分页</span><NButton v-if="cursor" @click="load(cursor)" :loading="loading">加载下一页</NButton></footer></section></template>
